In [1]:
import pandas as pd
import sqlite3

conn = sqlite3.connect("ecommerce_final.db")

In [2]:
query_1 = """
-- Query 1: Average price, rating, and stock by category
SELECT
    category,
    AVG(price) AS avg_price,
    AVG(rating) AS avg_rating,
    AVG(stock) AS avg_stock
FROM products
GROUP BY category
ORDER BY avg_rating DESC;
"""
pd.read_sql_query(query_1, conn)

               category     avg_price  avg_rating  avg_stock
0            mens-shoes    109.990000    4.602000  37.600000
1        womens-dresses    105.990000    4.114000  31.200000
2    sports-accessories     24.107647    4.014706  51.235294
3             furniture   1199.990000    4.006000  49.000000
4      womens-jewellery     24.990000    3.976667  42.666667
5             groceries      5.467778    3.911481  52.481481
6               tablets    483.323333    3.860000  67.000000
7    mobile-accessories    146.990000    3.851429  37.928571
8            fragrances     83.990000    3.826000  56.000000
9   kitchen-accessories     17.690000    3.820667  55.200000
10                 tops     29.990000    3.788000  49.000000
11      home-decoration     38.990000    3.784000  44.000000
12               beauty     13.390000    3.748000  78.400000
13           sunglasses     26.590000    3.726000  39.600000
14          smartphones    424.990000    3.698125  43.437500
15           motorcycle   7699.990000    3.666000  36.000000
16         mens-watches   8098.323333    3.660000  58.166667
17              laptops   1559.990000    3.622000  51.600000
18            skin-care     10.656667    3.620000  74.333333
19       womens-watches   6585.990000    3.476000  31.600000
20         womens-shoes     42.990000    3.402000  48.000000
21              vehicle  31199.990000    3.394000  68.200000
22          womens-bags    175.990000    3.360000  60.000000
23          mens-shirts     27.590000    3.180000  61.400000

Query 1: Average Product Metrics by Category

This query groups the products table by category and calculates the average price, average rating, and average stock for each category.

It matters because it provides a basic business summary of how categories differ in terms of pricing, customer satisfaction, and inventory levels.

The general takeaway is that categories are not all alike: some categories are more premium, some are rated more highly, and some hold more inventory than others.

In [3]:
query_2 = """
-- Query 2: Average quantity and discounted total by product_id
SELECT
    product_id,
    AVG(cart_item_quantity) AS avg_quantity,
    AVG(cart_item_discounted_total) AS avg_discounted_total
FROM cart_items
GROUP BY product_id
ORDER BY avg_discounted_total DESC;
"""
pd.read_sql_query(query_2, conn)

     product_id  avg_quantity  avg_discounted_total
0           167      5.000000         127918.960000
1           171      4.000000         118527.960000
2           168      3.000000          85743.870000
3           191      4.000000          61913.560000
4            97      4.000000          39344.763333
..          ...           ...                   ...
128          16      2.000000              3.515000
129          25      2.333333              2.973333
130          31      4.000000              2.770000
131          26      2.000000              1.605000
132          42      1.000000              0.960000

[133 rows x 3 columns]

Query 2: Average Cart Metrics by Product

This query groups the cart_items table by product ID and calculates the average quantity purchased and the average discounted total for each product.

It matters because it helps identify which individual products tend to contribute more value inside shopping carts.

The general takeaway is that some products generate much larger cart contributions than others, either because they are bought in higher quantities or because they have higher per-item value.

In [4]:
query_3 = """
-- Query 3: Join products and cart_items to analyze category-level cart performance
SELECT
    p.category,
    AVG(c.cart_item_quantity) AS avg_quantity,
    AVG(c.cart_item_discounted_total) AS avg_discounted_total
FROM cart_items c
JOIN products p
    ON c.product_id = p.product_id
GROUP BY p.category
ORDER BY avg_discounted_total DESC;
"""
pd.read_sql_query(query_3, conn)

               category  avg_quantity  avg_discounted_total
0               vehicle      4.000000         113849.342000
1        womens-watches      3.200000          20658.348000
2          mens-watches      3.250000          16790.860000
3            motorcycle      2.500000          11018.525000
4             furniture      4.500000           5691.925000
5               laptops      3.200000           4453.664000
6           smartphones      3.157895           1262.807368
7               tablets      2.000000           1148.260000
8    mobile-accessories      3.684211            398.824211
9        womens-dresses      2.750000            324.980000
10          womens-bags      3.333333            312.126667
11           fragrances      3.500000            255.252500
12           mens-shoes      2.833333            246.783333
13         womens-shoes      4.000000            196.680000
14                 tops      4.200000            123.162000
15      home-decoration      3.666667             94.036667
16           sunglasses      3.500000             88.121667
17          mens-shirts      2.750000             79.997500
18   sports-accessories      3.500000             76.641500
19     womens-jewellery      2.333333             58.980000
20            skin-care      5.000000             41.700000
21  kitchen-accessories      3.035714             41.610000
22               beauty      2.833333             30.948333
23            groceries      3.000000             11.509091

Query 3: Category-Level Cart Performance Using a Join

This query joins the cart_items table with the products table on product ID and then calculates average quantity and average discounted cart value by product category.

It matters because category-level cart performance cannot be measured from the cart data alone; the join is needed to connect cart behavior to product attributes.

The general takeaway is that some categories contribute more strongly to cart value than others, which can help an e-commerce analyst prioritize categories for merchandising or promotion.

In [5]:
query_4 = """
-- Query 4: Join products and cart_items to analyze brand-level cart performance
SELECT
    p.brand,
    AVG(c.cart_item_quantity) AS avg_quantity,
    AVG(c.cart_item_discounted_total) AS avg_discounted_total,
    AVG(p.rating) AS avg_rating
FROM cart_items c
JOIN products p
    ON c.product_id = p.product_id
GROUP BY p.brand
ORDER BY avg_discounted_total DESC
LIMIT 15;
"""
pd.read_sql_query(query_4, conn)

               brand  avg_quantity  avg_discounted_total  avg_rating
0           Chrysler          4.25         120875.710000      3.7275
1              Dodge          3.00          85743.870000      2.5800
2              Rolex          3.40          38331.768000      3.5000
3                IWC          3.00          13148.973333      2.9300
4        SpeedMaster          2.00          12025.480000      3.9400
5     Generic Motors          3.00          10011.570000      4.9100
6   Annibale Colombo          5.00           8731.400000      4.7700
7               Dell          5.00           7207.450000      2.6700
8             Huawei          3.50           4410.455000      4.9800
9           Longines          3.00           3760.170000      3.8700
10              Asus          2.00           2980.780000      3.9500
11       Bath Trends          4.00           2652.450000      3.5900
12      Fashion Gold          3.00           1931.260000      4.2400
13           Samsung          2.80           1701.788000      3.9760
14         ProVision          3.00           1264.620000      2.7800

Query 4: Brand-Level Cart Performance Using a Join

This query joins cart_items and products, groups the results by brand, and calculates average cart quantity, average discounted cart value, and average rating for each brand.

It matters because brands are often a key decision variable in e-commerce analysis, and this query shows which brands tend to generate stronger cart-level commercial performance.

The general takeaway is that higher-spending brands are not always the highest-rated brands, which suggests that brand positioning and pricing may influence cart behavior differently than customer ratings do.

In [6]:
query_5 = """
-- Query 5: Join products and cart_items and group into price buckets
SELECT
    CASE
        WHEN p.price < 25 THEN 'Low'
        WHEN p.price < 100 THEN 'Medium'
        ELSE 'High'
    END AS price_bucket,
    AVG(c.cart_item_quantity) AS avg_quantity,
    AVG(c.cart_item_discounted_total) AS avg_discounted_total
FROM cart_items c
JOIN products p
    ON c.product_id = p.product_id
GROUP BY price_bucket
ORDER BY avg_discounted_total DESC;
"""
pd.read_sql_query(query_5, conn)

  price_bucket  avg_quantity  avg_discounted_total
0         High      3.157895          15717.897544
1       Medium      3.392157            165.248039
2          Low      3.233333             30.182444

Query 5: Cart Performance by Price Bucket

This query joins cart_items and products, creates Low, Medium, and High price buckets using a CASE statement, and then calculates average quantity and average discounted cart value for each bucket.

It matters because it helps test whether cart behavior differs systematically by product price level.

The general takeaway is that products at different price tiers contribute to carts in different ways, and this can help analysts understand whether customers tend to spend through premium items or through larger quantities of lower-priced items.

In [7]:
query_6 = """
-- Query 6: Use a window function to rank products by average discounted cart item total
SELECT
    p.title,
    p.category,
    AVG(c.cart_item_discounted_total) AS avg_discounted_total,
    RANK() OVER (ORDER BY AVG(c.cart_item_discounted_total) DESC) AS product_rank
FROM cart_items c
JOIN products p
    ON c.product_id = p.product_id
GROUP BY p.title, p.category;
"""
pd.read_sql_query(query_6, conn)

,title,category,avg_discounted_total,product_rank
0,300 Touring,vehicle,127918.960000,1
1,Pacifica Touring,vehicle,118527.960000,2
2,Charger SXT RWD,vehicle,85743.870000,3
3,Rolex Cellini Moonphase,womens-watches,61913.560000,4
4,Rolex Datejust,mens-watches,39344.763333,5
...,...,...,...,...
128,Apple,groceries,3.515000,129
129,Green Bell Pepper,groceries,2.973333,130
130,Lemon,groceries,2.770000,131
131,Green Chili Pepper,groceries,1.605000,132
132,Water,groceries,0.960000,133

Query 6: Ranking Products by Average Discounted Cart Value

This query joins the two tables, calculates the average discounted cart item total for each product, and then uses a window function to rank products from highest to lowest.

It matters because window functions allow ranking without collapsing the logic into a simple top-N sort, and they are useful for identifying relative product performance.

The general takeaway is that a small number of products may account for a disproportionately large share of cart value.

In [8]:
query_7 = """
-- Query 7: Use a window function to rank categories by average cart item quantity
SELECT
    p.category,
    AVG(c.cart_item_quantity) AS avg_quantity,
    DENSE_RANK() OVER (ORDER BY AVG(c.cart_item_quantity) DESC) AS category_rank
FROM cart_items c
JOIN products p
    ON c.product_id = p.product_id
GROUP BY p.category;
"""
pd.read_sql_query(query_7, conn)

               category  avg_quantity  category_rank
0             skin-care      5.000000              1
1             furniture      4.500000              2
2                  tops      4.200000              3
3          womens-shoes      4.000000              4
4               vehicle      4.000000              4
5    mobile-accessories      3.684211              5
6       home-decoration      3.666667              6
7            sunglasses      3.500000              7
8    sports-accessories      3.500000              7
9            fragrances      3.500000              7
10          womens-bags      3.333333              8
11         mens-watches      3.250000              9
12       womens-watches      3.200000             10
13              laptops      3.200000             10
14          smartphones      3.157895             11
15  kitchen-accessories      3.035714             12
16            groceries      3.000000             13
17           mens-shoes      2.833333             14
18               beauty      2.833333             14
19       womens-dresses      2.750000             15
20          mens-shirts      2.750000             15
21           motorcycle      2.500000             16
22     womens-jewellery      2.333333             17
23              tablets      2.000000             18

Query 7: Ranking Categories by Average Quantity Purchased

This query joins cart_items and products, calculates the average quantity purchased for each category, and uses a window function to assign a dense rank.

It matters because it shows which categories tend to be purchased in larger quantities, which may differ from the categories that generate the highest dollar value.

The general takeaway is that quantity leadership and revenue leadership are not always the same, and both perspectives are useful for e-commerce decision-making.

In [9]:
query_8 = """
-- Query 8: Find products priced above the overall average price
SELECT
    product_id,
    title,
    category,
    price
FROM products
WHERE price > (
    SELECT AVG(price)
    FROM products
)
ORDER BY price DESC;
"""
pd.read_sql_query(query_8, conn)

    product_id                                 title        category     price
0          170                       Durango SXT RWD         vehicle  36999.99
1          168                       Charger SXT RWD         vehicle  32999.99
2          171                      Pacifica Touring         vehicle  31999.99
3          167                           300 Touring         vehicle  28999.99
4          169                  Dodge Hornet GT Plus         vehicle  24999.99
5          191               Rolex Cellini Moonphase  womens-watches  15999.99
6          115                          MotoGP CI.H1      motorcycle  14999.99
7           98                Rolex Submariner Watch    mens-watches  13999.99
8           96               Rolex Cellini Moonphase    mens-watches  12999.99
9           97                        Rolex Datejust    mens-watches  10999.99
10         192                  Rolex Datejust Women  womens-watches  10999.99
11          95         Rolex Cellini Date Black Dial    mens-watches   8999.99
12         114                         Kawasaki Z800      motorcycle   8999.99
13         117                  Sportbike Motorcycle      motorcycle   7499.99
14         190         IWC Ingenieur Automatic Steel  womens-watches   4999.99
15         113                    Generic Motorcycle      motorcycle   3999.99
16         116                    Scooter Motorcycle      motorcycle   2999.99
17          12                 Annibale Colombo Sofa       furniture   2499.99
18          78  Apple MacBook Pro 14 Inch Space Grey         laptops   1999.99
19          11                  Annibale Colombo Bed       furniture   1899.99
20          79   Asus Zenbook Pro Dual Screen Laptop         laptops   1799.99

Query 8: Products Priced Above the Overall Average

This query uses a subquery to calculate the overall average product price and then returns only the products priced above that benchmark.

It matters because subqueries are a useful way to compare individual observations against an overall summary metric.

The general takeaway is that above-average priced products can be isolated and studied separately to understand premium positioning in the catalog.

In [10]:
query_9 = """
-- Query 9: Find cart items whose discounted total exceeds the average cart item discounted total
SELECT
    cart_id,
    product_id,
    cart_item_quantity,
    cart_item_discounted_total
FROM cart_items
WHERE cart_item_discounted_total > (
    SELECT AVG(cart_item_discounted_total)
    FROM cart_items
)
ORDER BY cart_item_discounted_total DESC;
"""
pd.read_sql_query(query_9, conn)

    cart_id  product_id  cart_item_quantity  cart_item_discounted_total
0        37         171                   5                   148159.95
1         7         167                   5                   127918.96
2        30         171                   4                   118527.96
3        40         171                   3                    88895.97
4         1         168                   3                    85743.87
5         9         191                   4                    61913.56
6        32          97                   5                    49180.96
7        39          97                   4                    39344.76
8         6          97                   3                    29508.57
9        10         190                   5                    21914.96
10        8         117                   2                    12025.48
11        3          98                   1                    11710.99
12       42         113                   3                    10011.57
13       32         190                   2                     8765.98
14       48         190                   2                     8765.98
15       15          11                   5                     8731.40
16       23          82                   5                     7207.45
17        5          80                   5                     6300.65

Query 9: Cart Items Above the Average Discounted Cart Value

This query uses a subquery to calculate the average discounted cart item total across all cart items and then returns only the rows that exceed that value.

It matters because it helps identify high-value cart-item observations and demonstrates another use of subqueries for threshold-based filtering.

The general takeaway is that only a subset of cart items account for above-average value, which may be useful for identifying priority products or customer purchase patterns.

In [11]:
query_10 = """
-- Query 10: Grouped business summary by category
SELECT
    p.category,
    COUNT(*) AS row_count,
    AVG(p.price) AS avg_price,
    AVG(p.rating) AS avg_rating,
    AVG(c.cart_item_quantity) AS avg_quantity,
    AVG(c.cart_item_discounted_total) AS avg_discounted_total
FROM cart_items c
JOIN products p
    ON c.product_id = p.product_id
GROUP BY p.category
ORDER BY avg_discounted_total DESC;
"""
pd.read_sql_query(query_10, conn)

,category,row_count,avg_price,avg_rating,avg_quantity,avg_discounted_total
0,vehicle,5,31599.990000,3.498000,4.000000,113849.342000
1,womens-watches,5,6359.990000,3.372000,3.200000,20658.348000
2,mens-watches,8,6096.240000,3.763750,3.250000,16790.860000
3,motorcycle,2,5749.990000,4.425000,2.500000,11018.525000
4,furniture,2,1349.990000,4.180000,4.500000,5691.925000
5,laptops,5,1619.990000,4.046000,3.200000,4453.664000
6,smartphones,19,423.674211,3.548421,3.157895,1262.807368
7,tablets,2,599.990000,4.680000,2.000000,1148.260000
8,mobile-accessories,19,117.411053,3.782105,3.684211,398.824211
9,womens-dresses,4,132.490000,4.132500,2.750000,324.980000
10,womens-bags,3,233.323333,2.850000,3.333333,312.126667
11,fragrances,4,74.990000,3.412500,3.500000,255.252500
12,mens-shoes,6,109.990000,4.616667,2.833333,246.783333
13,womens-shoes,2,49.990000,3.260000,4.000000,196.680000
14,tops,5,29.990000,3.788000,4.200000,123.162000
15,home-decoration,6,30.823333,4.113333,3.666667,94.036667
16,sunglasses,6,25.990000,3.608333,3.500000,88.121667
17,mens-shirts,4,32.490000,3.550000,2.750000,79.997500
18,sports-accessories,20,26.990000,3.981500,3.500000,76.641500
19,womens-jewellery,3,28.323333,3.830000,2.333333,58.980000
20,skin-care,1,8.990000,3.190000,5.000000,41.700000
21,kitchen-accessories,28,13.954286,3.708571,3.035714,41.610000
22,beauty,6,12.490000,3.503333,2.833333,30.948333
23,groceries,33,3.923333,3.896970,3.000000,11.509091

Query 10: Category-Level Business Summary

This query joins cart_items and products and creates a broad business summary by category, including row count, average price, average rating, average quantity, and average discounted cart value.

It matters because it combines product-level and cart-level metrics in one place and provides a compact summary for comparing overall category performance.

The general takeaway is that categories differ across several dimensions at once, and decision-makers should consider both customer response and commercial contribution when evaluating category strength.